/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gymmanagementsystem;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author quach
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        addMember = new javax.swing.JMenu();
        editMember = new javax.swing.JMenu();
        trainers = new javax.swing.JMenu();
        payments = new javax.swing.JMenu();
        payments1 = new javax.swing.JMenu();
        logOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("Добро пожаловать");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setText("Информационно-справочная");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setText("спортивным клубом");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setText("система для управления");

        addMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addmembericon.png"))); // NOI18N
        addMember.setText("Добавить пользователя");
        addMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMemberMouseClicked(evt);
            }
        });
        jMenuBar1.add(addMember);

        editMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/managemembericon.png"))); // NOI18N
        editMember.setText("Управлять");
        editMember.setToolTipText("");
        editMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMemberMouseClicked(evt);
            }
        });
        jMenuBar1.add(editMember);

        trainers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trainericon.png"))); // NOI18N
        trainers.setText("Тренера");
        trainers.setToolTipText("");
        trainers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trainersMouseClicked(evt);
            }
        });
        jMenuBar1.add(trainers);

        payments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/listicon.png"))); // NOI18N
        payments.setText("Список членов");
        payments.setToolTipText("");
        payments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentsMouseClicked(evt);
            }
        });
        jMenuBar1.add(payments);

        payments1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paymentsicon.png"))); // NOI18N
        payments1.setText("Платежи");
        payments1.setToolTipText("");
        payments1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payments1MouseClicked(evt);
            }
        });
        jMenuBar1.add(payments1);

        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logouticon.png"))); // NOI18N
        logOut.setText("Log out");
        logOut.setToolTipText("");
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        int logout = JOptionPane.showConfirmDialog(null, "Log out?", "Select",JOptionPane.YES_NO_CANCEL_OPTION);
        if (logout==0){
            setVisible(false);
            new login().setVisible(true);
        }
        
    }//GEN-LAST:event_logOutMouseClicked

    private void addMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMemberMouseClicked
        setVisible(false);
        new newMember().setVisible(true);
    }//GEN-LAST:event_addMemberMouseClicked

    private void editMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMemberMouseClicked
        setVisible(false);
        new editMember().setVisible(true);
    }//GEN-LAST:event_editMemberMouseClicked

    private void trainersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainersMouseClicked
        setVisible(false);
        new trainer().setVisible(true);
    }//GEN-LAST:event_trainersMouseClicked

    private void paymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentsMouseClicked
        setVisible(false);
        new memberList().setVisible(true);
    }//GEN-LAST:event_paymentsMouseClicked

    private void payments1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payments1MouseClicked
        setVisible(false);
        new payment().setVisible(true);
    }//GEN-LAST:event_payments1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu addMember;
    private javax.swing.JMenu editMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu logOut;
    private javax.swing.JMenu payments;
    private javax.swing.JMenu payments1;
    private javax.swing.JMenu trainers;
    // End of variables declaration//GEN-END:variables
}
